### ISSUE TITLE
[FEATURE REQUEST] 增加直接返回 String 作为结果的方法

### ISSUE THREAD

**Issue by Qubik65536** [FOSScope/libhtmlfilter#1]
https://github.com/FOSScope/Toolkit 需要直接将带有 HTML 内容的 String 给 html2md 转换，不需要将 HTML 输出到一个文件夹里，希望增加一个直接将过滤后 HTML 作为 String 返回的方法

**Comment by cysnies** [comment]
感谢，已添加。
#8638d3186a7ed441a0aee56fefd67ab28e6eb30e
